### PR TITLE
LNURL-auth support

### PR DESCRIPTION
**Pull request by bumi**
some services where this can be tested: https://github.com/fiatjaf/awesome-lnurl#lnurl-auth

### CODE REVIEW

**Comment by dylancom** [comment]
Cool, this can me merged! Tested with: https://fortune.lngames.net/ & https://stacker.news/

**Comment by bumi** [comment]
ah. we should first merge your PR #141 (can not merge this PR into your fork it seems?)

**Comment by dylancom** [comment]
Yes it seems. Now it's merged into a local copy that doesn't have all commits from my fork.

**Comment by bumi** [comment]
yep, I opened a PR in your fork repo.

**Pull request merged**
