### PR TITLE
Lock account from options screen

### PR DESCRIPTION
**Pull request by dylancom**

### CODE REVIEW

**Comment by bumi** [comment]
👍 I think we should call it "lock" or something like that. the user is not really logged in.

**Comment by bumi** [comment]
was wondering if we need a lock button also on the popup.... what do you think @johnsBeharry? 
Should the user often lock the extension wallet? or is the default to keep it unlocked?

**Comment by dylancom** [comment]
Might have a "user" button on the top right that can open a menu to "lock account", "edit account" and such? (Just like here on GitHub etc.)

**Comment by bumi** [comment]
actually I think that’s a good idea.
and the link to the options page could be a “options/settings” link in that menu.

**Comment by dylancom** [comment]
I created a `<UserMenu />` component which now contains the buttons "Options" and "Lock".

**Comment by bumi** [comment]
that's great and can be now easily extended. 👍

**Pull request merged**
