### PR TITLE
Use a different extension icon

### PR DESCRIPTION
**Pull request by bumi**
We need a logo soon (and a name :D) 
This is an icon from the figma designs: https://www.figma.com/file/xEPJFGFdc3HD0JS1ax2IpH/Lightning-Browser-Extension?node-id=94%3A0

image

### CODE REVIEW

**Comment by chris-aeviator** [comment]
Will ask my partner if he can contribute - any inputs?

**Comment by bumi** [comment]
not really, I just used one from the figma designs to not use that default one any longer :)

I guess that leads us to a broader design/identity question... 👩‍🎨 🎨

**Comment by chris-aeviator** [comment]
For the identity I think it's  not too bad to be the lightning browser extension. I realized yday that Joule doesnt even show up when you search for "lightning" in the mozilla addons.

**Comment by bumi** [comment]
Joule is dead: 
https://github.com/joule-labs/joule-extension/issues/260
https://github.com/joule-labs/joule-extension/pull/269
https://github.com/joule-labs/joule-extension/pull/268

**Comment by chris-aeviator** [comment]
open source is so hard these days...thanks for making that clear, did not know that yet

**Pull request closed without merging**
